<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Admin CP' => '',
  'Author' => '',
  'Caching (sec.)' => '',
  'Control Panel' => '',
  'Description' => '',
  'Go to Settings' => '',
  'Google Analytics Account (UA-XXXXXX-X)' => '',
  'Include Captcha in the registration form' => '',
  'Include activation Email' => '',
  'Manage' => '',
  'Manually rename directory on FTP after save' => '',
  'Maximum number of characters in the Captcha' => '',
  'Minimum number of characters in the Captcha' => '',
  'Name' => '',
  'Settings' => '',
  'Site Email' => '',
  'Site Name' => '',
  'The minimum length of the password' => '',
  'Upload Directory' => '',
  'module|modules' => '',
  'Add' => '',
  'Settings' => '',
  'list' => '',
);
