<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Access Type' => '',
  'Active' => '',
  'Administrator' => '',
  'All posts' => '',
  'Author' => '',
  'Blocked' => '',
  'Blog' => '',
  'Blog "{blog}" not found!' => '',
  'Blog added!' => '',
  'Blog deleted!' => '',
  'Blog updated!' => '',
  'Blogs' => '',
  'Changed' => '',
  'Comment Status' => '',
  'Content' => '',
  'Create' => '',
  'Create Post' => '',
  'Create Time' => '',
  'Deleted' => '',
  'Description' => '',
  'ID' => '',
  'Keywords' => '',
  'Link' => '',
  'Manage' => '',
  'Manage Posts' => '',
  'Manage Users' => '',
  'Manage blogs, posts and members' => '',
  'Member' => '',
  'Members' => '',
  'Moderator' => '',
  'No' => '',
  'Note' => '',
  'Post not found!' => '',
  'Posts' => '',
  'Private' => '',
  'Public' => '',
  'Publish Time' => '',
  'Read more →' => '',
  'Role' => '',
  'Save' => '',
  'Search' => '',
  'Status' => '',
  'String contains illegal characters. Allowed: {attribute}' => '',
  'Tagged' => '',
  'Tags' => '',
  'Title' => '',
  'Type' => '',
  'URL' => '',
  'Update' => '',
  'Update Time' => '',
  'User' => '',
  'User already in blog!' => '',
  'Yes' => '',
  'member|members' => '',
  'post|posts' => '',
  'select blog' => '',
  'unknown' => '',
  '{n} Comment|{n} Comments' => '',
);
