<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Alert text after send message from full form' => '',
  'City' => '',
  'Contact form and mail settings' => '',
  'Contacts' => '',
  'Enable send mail via SMTP?' => '',
  'Enter Code' => '',
  'For example disable on McHost.ru. Option worked only throw PHP mail(), not SMTP' => '',
  'Full form class name' => '',
  'Message Text' => '',
  'Message from {site}' => '',
  'Message title' => '',
  'Message title of full form' => '',
  'Module for sending messages from site' => '',
  'Only for simple form. Anti-spam.' => '',
  'Problem with sending message. Write to administrator:' => '',
  'Required Captcha?' => '',
  'SMTP Server Host' => '',
  'SMTP login' => '',
  'SMTP password' => '',
  'SMTP port' => '',
  'SMTP type connection' => '',
  'Send' => '',
  'Set from email address' => '',
  'Thanks for message!' => '',
  'You name?' => '',
  'Do not change unless you know' => '',
  'Questionnaire site' => '',
);
