<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<i class="icon-search"></i> Search <span class="caret"></span>' => '',
  'Add' => '',
  'Add photo…' => '',
  'Adding' => '',
  'Album' => '',
  'Albums' => '',
  'Author' => '',
  'Change selected' => '',
  'Changing' => '',
  'Close' => '',
  'Create and manage albums with photos' => '',
  'Created' => '',
  'Description' => '',
  'Directory for photos' => '',
  'Edit Data' => '',
  'Fields with <span class="required">*</span> is required.' => '',
  'File' => '',
  'Gallery' => '',
  'Hidden' => '',
  'Hidden. Publish?' => '',
  'If you use Gallery with Folio theme (default), change CSS:
					<br/> .galleria-thumbnails .galleria-image {width: 130px}
					<br/>File: ./extensions/galleria/assets/themes/folio/galleria.folio.css
					<br/>else thumbnail will be show in 130px width' => '',
  'Keywords' => '',
  'Manage' => '',
  'Max photo height after upload' => '',
  'Max photo width after upload' => '',
  'Max thumb photo width after upload' => '',
  'Name' => '',
  'Order' => '',
  'Photos' => '',
  'Published' => '',
  'Published. Hide?' => '',
  'Remove selected' => '',
  'Save' => '',
  'Search' => '',
  'Select All' => '',
  'Slug' => '',
  'Status' => '',
  'Supported photo formats' => '',
  'Title' => '',
  'Type' => '',
  'Update User' => '',
);
