<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '- anything -' => '',
  '<i class="icon-search"></i> Search <span class="caret"></span>' => '',
  'Add' => '',
  'Adding' => '',
  'All' => '',
  'Author' => '',
  'Changing' => '',
  'Count of news on main page' => '',
  'Created' => '',
  'Date' => '',
  'Draft' => '',
  'Fields with <span class="required">*</span> is required.' => '',
  'Full Text' => '',
  'META Description' => '',
  'META Keywords' => '',
  'Manage' => '',
  'Manage Site News' => '',
  'Max photo height after upload' => '',
  'Max photo width after upload' => '',
  'Max thumb photo width after upload' => '',
  'News' => '',
  'News Added!' => '',
  'News Not Found!' => '',
  'News announce (short)' => '',
  'On Moderation' => '',
  'Only for registered users' => '',
  'Photo formats' => '',
  'Photo upload directory' => '',
  'Picture' => '',
  'Published' => '',
  'Save' => '',
  'Search' => '',
  'Short Text' => '',
  'Slug' => '',
  'Status' => '',
  'Text' => '',
  'Title' => '',
  'Update Time' => '',
  'Update User' => '',
);
