<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '(not) or' => '',
  '(не равно) или' => '',
  '- no parent page -' => '',
  '<i class="icon-search"></i> Search Pages <span class="caret"></span>' => '',
  '<i class="icon-search"></i> Поиск меню <span class="caret"></span>' => '',
  'Add' => '',
  'Adding' => '',
  'Adding Page' => '',
  'Additional' => '',
  'All' => '',
  'Annotation to a page' => '',
  'Articles — shows a list of subpages' => '',
  'Author' => '',
  'Catalog module' => '',
  'Count Results Per Page' => '',
  'Created' => '',
  'Draft' => '',
  'Editing Page' => '',
  'Full article' => '',
  'General' => '',
  'Link' => '',
  'List Pages' => '',
  'META Description' => '',
  'META Keywords' => '',
  'Main Page (slug)' => '',
  'Manage' => '',
  'Manage Pages' => '',
  'Manage Site Pages' => '',
  'Name in Menu' => '',
  'On Moderation' => '',
  'Only for registered users' => '',
  'Only small image (thumbnail)' => '',
  'Open on Site' => '',
  'Page Added!' => '',
  'Page Not Found or Deleted!' => '',
  'Pages' => '',
  'Parent' => '',
  'Parent Level' => '',
  'Picture' => '',
  'Preview' => '',
  'Published' => '',
  'Save' => '',
  'Search' => '',
  'See on Site' => '',
  'Settings' => '',
  'Show thumbnail' => '',
  'Sorting' => '',
  'Status' => '',
  'Text' => '',
  'Title' => '',
  'Type' => '',
  'Update user' => '',
  'Updated' => '',
  'Use HTML Editor' => '',
  'Use Symbols' => '',
  'Viewing Page' => '',
  'Через запятую' => '',
  'в начале строки поиска' => '',
  'меньше или равно)' => '',
);
