<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '',
  '$_SERVER variable' => '',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '',
  'APC extension' => '',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => '',
  'CProfileLogRoute found a mismatching code block "{token}". Make sure the calls to Yii::beginProfile() and Yii::endProfile() be properly nested.' => '',
  'Ctype extension' => '',
  'DOM extension' => '',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '',
  'GD extension with<br />FreeType support<br />or ImageMagick<br />extension with<br />PNG support' => '',
  'GD installed,<br />FreeType support not installed' => '',
  'GD or ImageMagick not installed' => '',
  'Mcrypt extension' => '',
  'Memcache extension' => '',
  'No' => '',
  'PCRE extension' => '',
  'PDO MSSQL extension (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)' => '',
  'PDO MSSQL extension (pdo_dblib)' => '',
  'PDO MSSQL extension (pdo_mssql)' => '',
  'PDO MySQL extension' => '',
  'PDO Oracle extension' => '',
  'PDO PostgreSQL extension' => '',
  'PDO SQLite extension' => '',
  'PDO extension' => '',
  'PHP 5.1.0 or higher is required.' => '',
  'PHP version' => '',
  'Powered by {yii}.' => '',
  'Property "{class}.{property}" is not defined.' => '',
  'Reflection extension' => '',
  'SOAP extension' => '',
  'SPL extension' => '',
  'The controller path "{path}" is not a valid directory.' => '',
  'The format of {attribute} is invalid.' => '',
  'The layout path "{path}" is not a valid directory.' => '',
  'The view path "{path}" is not a valid directory.' => '',
  'This is required by encrypt and decrypt methods.' => '',
  'This is required if you are using MSSQL database from GNU/Linux or other UNIX.' => '',
  'This is required if you are using MSSQL database from MS Windows' => '',
  'This is required if you are using MSSQL database with the driver provided by Microsoft.' => '',
  'This is required if you are using MySQL database.' => '',
  'This is required if you are using Oracle database.' => '',
  'This is required if you are using PostgreSQL database.' => '',
  'This is required if you are using SQLite database.' => '',
  'To use memcached set <a href="http://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => '',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => '',
  'Yes' => '',
  'You are not authorized to perform this action.' => '',
  'Your request is invalid.' => '',
  '{attribute} "{value}" is invalid.' => '',
  '{attribute} cannot be blank.' => '',
  '{class} and its behaviors do not have a method or closure named "{name}".' => '',
);
